print('========= Desafio 03 =========')
num1 = int(input('Digite um número qualquer? '))
num2 = int(input('Digite um outro número diferente do primeiro '))
s = num1 + num2
print ('A soma de {} e {} é {}'.format(num1,num2,s))

print('========= Desafio 04 =========')
n = input ('Digite qualquer coisa! ')
print (n.isalnum())
print (n.isalpha())
print (n.isascii())
print (n.isdecimal())
print (n.isdigit())
print (n.isidentifier())
print (n.islower())
print (n.isnumeric())
print (n.isprintable())
print (n.isspace())
print (n.istitle())
print (n.isupper())